<?php
$title = 'Add new Blog Post';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('blog', array('action' => 'create')));
$form->prepare();

echo $this->form()->openTag($form) . PHP_EOL;

echo $this->formRow($form->get('blog-post')->get('title')) . PHP_EOL;
//echo $this->formRow($form->get('tags')) . PHP_EOL;
echo $this->formInput($form->get('submit')) . PHP_EOL;
echo $this->form()->closeTag($form) . PHP_EOL;

