<?php
$title = 'Blog Posts';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('blog', array(
        'action'=>'create'));?>">
        Create new Blog Post
    </a>
</p>

<table class="table">
    <tr>
        <th>Title</th>
        <th>Tags</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($blogPosts as $p) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($p->title);?></td>

            <td><?php //echo $this->escapeHtml($album->artist);?></td>

            <td>
                <a href="<?php echo $this->url('blog',
                    array('action'=>'update', 'id' => $p->id));?>">
                    Update
                </a>
                <a href="<?php echo $this->url('blog',
                    array('action'=>'delete', 'id' => $p->id));?>">
                    Delete
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
