<?php 
$title = 'Blog Posts';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('blog', array(
        'action'=>'create'));?>">
        Create new Blog Post
    </a>
</p>

<!--<table class="table">-->
<!--    <tr>-->
<!--        <th>Title</th>-->
<!--        <th>Artist</th>-->
<!--        <th>&nbsp;</th>-->
<!--    </tr>-->
<!--    --><?php //foreach($albums as $album) : ?>
<!--        <tr>-->
<!--            <td>--><?php //echo $this->escapeHtml($album->title);?><!--</td>-->
<!--            <td>--><?php //echo $this->escapeHtml($album->artist);?><!--</td>-->
<!--            <td>-->
<!--                <a href="--><?php //echo $this->url('album',
//                    array('action'=>'edit', 'id' => $album->id));?><!--">Edit</a>-->
<!--                <a href="--><?php //echo $this->url('album',
//                    array('action'=>'delete', 'id' => $album->id));?><!--">Delete</a>-->
<!--            </td>-->
<!--        </tr>-->
<!--    --><?php //endforeach; ?>
<!--</table>-->
